#!/bin/bash
source "$CONFIG_DIR/colors.sh"
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=32        \
                 blur_radius=30   \
                 position=top     \
                 sticky=off       \
                 padding_left=10  \
                 padding_right=10 \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=2
  padding_right=1
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:14.0"
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=6
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=6
)
sketchybar --default "${default[@]}"

# --- Right side items
# source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/wifi.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
